---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: mfe-shell
spec:
  interval: 10m
  url: oci://ghcr.io/polecatworks/mfe-shell/helm/nginx-view
  ref:
    semver: ">= 0.1.x-0"
    semverFilter: .*-main
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mfe-shell
spec:
  releaseName: mfe-shell
  chartRef:
    kind: OCIRepository
    name: mfe-shell
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/polecatworks/mfe-shell-mfe-shell
      tag: main
      pullPolicy: Always # Dev ONLY
    config:
      contents:
        mfe.json: |
          {
            "mfe1": "/mfe1/remoteEntry.json"
          }
        auth-config.json: |
          {
            "issuer": "http://keycloak.k8s/auth/realms/dev",
            "redirectUri": "/index.html",
            "clientId": "mfe-shell",
            "responseType": "code",
            "scope": "openid profile email offline_access",
            "useSilentRefresh": true,
            "showDebugInformation": true,
            "timeoutFactor": 0.01,
            "requireHttps": false,
            "skipIssuerCheck": true,
            "strictDiscoveryDocumentValidation": false
          }
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mfe1
spec:
  releaseName: mfe1
  chartRef:
    kind: OCIRepository
    name: mfe-shell
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/polecatworks/mfe-shell-mfe1
      tag: main
      pullPolicy: Always # Dev ONLY
