---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: mfe-shell
spec:
  interval: 10m
  url: oci://ghcr.io/polecatworks/mfe-shell/helm/nginx-view
  ref:
    semver: ">= 0.1.x-0"
    semverFilter: .*-main
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mfe-shell
spec:
  releaseName: mfe-shell
  chartRef:
    kind: OCIRepository
    name: mfe-shell
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/polecatworks/mfe-shell-mfe-shell
      tag: main
      pullPolicy: Always # Dev ONLY
    config:
      configs:
        default.conf.template: |
          server {
            listen 8080;
            server_name localhost;
            root /usr/share/nginx/html;

            # 1. Health Checks (High Priority)
            location /alive { return 200; access_log off; }
            location /ready { return 200; access_log off; }

            # 2. MFE Shell logic. Serve index.html if we hit a 404
            location / {
                alias /usr/share/nginx/html/;
                index  index.html index.htm;
                try_files $uri $uri/ /index.html;
            }
            error_page  404              /index.html;

            # 3. General Static Files
            location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|json)$ {
                expires 1y;
                add_header Cache-Control "public, no-transform";
                add_header 'Access-Control-Allow-Origin' '*';
                # Note: If a file is in /mfe1/, it was already handled by the ^~ block above
            }

            # 4. SPA Fallback
            location / {
                try_files $uri $uri/ /index.html;
            }
          }
      contents:
        mfe.json: |
          {
            "mfe1": "/mfe1/remoteEntry.json"
          }
        auth-config.json: |
          {
            "issuer": "http://keycloak.k8s/auth/realms/dev",
            "redirectUri": "/index.html",
            "clientId": "mfe-shell",
            "responseType": "code",
            "scope": "openid profile email offline_access",
            "useSilentRefresh": true,
            "showDebugInformation": true,
            "timeoutFactor": 0.01,
            "requireHttps": false,
            "skipIssuerCheck": true,
            "strictDiscoveryDocumentValidation": false
          }
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mfe1
spec:
  releaseName: mfe1
  chartRef:
    kind: OCIRepository
    name: mfe-shell
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/polecatworks/mfe-shell-mfe1
      tag: main
      pullPolicy: Always # Dev ONLY
    env:
      - name: SERVE_ROOT
        value: /mfe1
